server.port: ${SERVER_PORT:8083}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka/}
    enabled: true

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/users}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:}