server.port: ${SERVER_PORT:8084}

eureka:
  instance:
    preferIpAddress: true
    healthCheckUrlPath: /actuator/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka/}
    enabled: true
    registryFetchIntervalSeconds: 1


spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}